# TODOs:
# 1. Make magic values like folder paths variable values that can be accessed from bash or ps.
#
# 2. We need a way to identify which version of the asset/framework we currently have in order to
#    correctly name the folder/zip package.
#    One suggestion for enabling this is to have a manifest file that represents each asset/framework.
#
# 3. We need a way to only zip modules/framework based on changes. I.e we need to identify which asset has changed.
#
# 4. Need to determine what we will do with schema files. Should they also be packaged in the zip as well?
#
# 5. This file only handles the framework and modules. Missing packages zipping.

# Make the workflow be triggered manually for now
name: Generate Zipped Artifacts
run-name: Generate Zipped Artifacts by @${{ github.actor }}
on: push #TODO: change to workflow_dispatch

jobs:
  ZipArtifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Temp Folders
        run: |
          mkdir -p ./tmp/framework
          mkdir -p ./tmp/modules
          mkdir -p ./tmp/archives
      - name: Zip Framework
        run: |
          cp -r framework ./tmp/framework
          rm -rf ./tmp/framework/test_data
          cp setup.sh ./tmp/framework
          cp README.md ./tmp/framework
          zip -r ./tmp/archives/framework.zip ./tmp/framework/*
      - name: Zip Modules
        run: |
          for dir in modules/module_catalog/*/
          do
            cp -r ${dir} ./tmp/modules
            echo "Removing docs folder..."
            rm -rf ./tmp/modules/${dir}/docs
            zip -r ./tmp/archives/$(basename ${dir}).zip ./tmp/modules/${dir}/*
          done
          ls -al ./tmp/archives/
        