# Make the workflow be triggered manually for now
name: Generate Zipped Artifacts
run-name: Generate Zipped Artifacts by @${{ github.actor }}
on: push #TODO: change to workflow_dispatch

jobs:
  zip_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello, World
        run: echo 'Hello, World!'